config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :inboxes do
    resources :messages, only: %i[new create destroy] , module: :inboxes do
      member do 
        patch :upvote
      end
    end
  end

  root 'static_pages#landing_page'
  get 'pricing', to: 'static_pages#pricing'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inbox.rb
# frozen_string_literal: true

class Inbox < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  MIN_NAME = 6
  MAX_NAME = 100

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { in: MIN_NAME..MAX_NAME }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :inbox, counter_cache: true
  belongs_to :user

  MIN_NAME = 5
  MAX_NAME = 2000

  validates :body, presence: true
  # validates :body, uniqueness:{scope: :inbox_id}
  validates :body, length: { in: MIN_NAME..MAX_NAME }
  acts_as_votable
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :inboxes, dependent: :destroy
  # has_many :messages,through: :inboxes,
  # has_many :message, dependent: :destroy
  acts_as_voter
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/inboxes/messages_controller.rb
class Inboxes::MessagesController < ApplicationController
  before_action :set_inbox
  before_action :set_message, only: %i[destroy, upvote ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = @inbox.messages.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = @inbox.messages.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @inbox, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to @inbox, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def upvote
    flash[:notice] = 'upvoted'
    if current_user.voted_up_on? @message
        @message.downvote_from current_user
    elsif current_user.voted_down_on? @message
        @message.liked_by current_user
    else
      @message.liked_by current_user
    end 
    redirect_to @inbox
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = @inbox.messages.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:body).merge(user: current_user)
    end
    def set_inbox
      @inbox = Inbox.find(params[:inbox_id])
    end
end

app/controllers/inboxes_controller.rb
# frozen_string_literal: true

class InboxesController < ApplicationController
  before_action :set_inbox, only: %i[show edit update destroy]

  # GET /inboxes or /inboxes.json
  def index
    @inboxes = Inbox.all
  end

  # GET /inboxes/1 or /inboxes/1.json
  def show; end

  # GET /inboxes/new
  def new
    @inbox = Inbox.new
  end

  # GET /inboxes/1/edit
  def edit; end

  # POST /inboxes or /inboxes.json
  def create
    @inbox = current_user.inboxes.new(inbox_params)

    respond_to do |format|
      if @inbox.save
        format.html { redirect_to inbox_url(@inbox), notice: 'Inbox was successfully created.' }
        format.json { render :show, status: :created, location: @inbox }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inboxes/1 or /inboxes/1.json
  def update
    respond_to do |format|
      if @inbox.update(inbox_params)
        format.html { redirect_to inbox_url(@inbox), notice: 'Inbox was successfully updated.' }
        format.json { render :show, status: :ok, location: @inbox }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inboxes/1 or /inboxes/1.json
  def destroy
    @inbox.destroy

    respond_to do |format|
      format.html { redirect_to inboxes_url, notice: 'Inbox was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_inbox
    @inbox = Inbox.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def inbox_params
    params.require(:inbox).permit(:name)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:body, :inbox_id, :user_id)
    end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!
  def landing_page; end

  def pricing; end

  def privacy; end

  def terms; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/inboxes_helper.rb
# frozen_string_literal: true

module InboxesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/inboxes/_form.html.erb
<%= form_with(model: inbox) do |form| %>
 <%= render 'shared/errors', form: form %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inboxes/_inbox.html.erb
<div id="<%= dom_id inbox %>" class="scaffold_record">
  <p>
    <strong>Name:</strong>
    <h3><%=link_to  inbox.name,inbox %></h3>
  </p>
  <%= link_to "Edit this inboxes", edit_inbox_path(inbox) %></p>
  <%= button_to "Destroy this inbox", inbox_path(inbox), method: :delete %>
  
  Message: 
    <%= inbox.messages_count%>
    <br>
  
  <i>
  by
  <%= inbox.user.email%>
  on
  <%= inbox.created_at.strftime('%d/%b/%Y')%>
  </i>
   
</div>

app/views/inboxes/edit.html.erb
<h1>Editing inbox</h1>

<%= render "form", inbox: @inbox %>

<br>

<div>
  <%= link_to "Cancel", inboxes_path %>
</div>

app/views/inboxes/index.html.erb
<h1>Inboxes: <%= @inboxes.count %></h1>

<div id="inboxes">
  <% @inboxes.each do |inbox| %>
    <%= render inbox %>
    
  <% end %>
</div>

app/views/inboxes/messages/_form.html.erb
<%= form_with(model: [@inbox,message]) do |form| %>
  <%= render 'shared/errors', form: form %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inboxes/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Body:</strong>
    <%= simple_format(message.body) %>
  </p>

  <p>
    <strong>Inbox:</strong>
    <%= link_to message.inbox.name ,message.inbox %>
  </p>

  <%= button_to 'Upvote',[:upvote,@inbox,message],
                method: :patch
                %>
      <%= message.cached_votes_total %>
      <%= message.cached_votes_score %>
      <%= message.cached_votes_up %>
      <%= message.cached_votes_down %>
      <%= message.cached_weighted_score %>
      <%= message.cached_weighted_total %>
      <%= message.cached_weighted_average %>
  

  <p>
    <strong>User:</strong>
    <%= message.user.email %>
  </p>
<%= button_to "Destroy ", inbox_message_path(@inbox,message), method: :delete %>
</div>

app/views/inboxes/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to Inbox", @inbox %>
</div>

app/views/inboxes/new.html.erb
<h1>New inbox</h1>

<%= render "form", inbox: @inbox %>

<br>

<div>
  <%= link_to "Cancel", inboxes_path %>
</div>

app/views/inboxes/show.html.erb
<%= render @inbox %>
<div>
  <%= link_to "Edit this inbox", edit_inbox_path(@inbox) %> |
  
</div>

<h1>
Messages 
<%=@inbox.messages_count%> 
</h1>

<%= link_to 'New Message' , [:new,@inbox, :message]%>
<%= render partial: 'inboxes/messages/message',collection: @inbox.messages%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=Rails.application.class.module_parent.name%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      
    <%=render 'shared/flash'%>
    <%= render 'shared/navigation'%>
    <%= yield %>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :inbox_id, style: "display: block" %>
    <%= form.text_field :inbox_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/shared/_errors.html.erb
<% if form.object.errors.any? %>
    <div style="color: red">
      <h4><%= pluralize(form.object.errors.count, "error") %> prohibited this record from being saved:</h4>

      <ul>
        <% form.object.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value|%>
    <%key %>
    <%value%>
    <%=content_tag :div,value, id: "#{key}"%>
<%end%>

app/views/shared/_footer.html.erb
<hr>
<center>
<%= link_to_unless_current 'Pricing',pricing_path %>
  <%= link_to_unless_current 'Terms',terms_path %>
  <%= link_to_unless_current 'Privacy',privacy_path %>
  
  </center>

app/views/shared/_navigation.html.erb
<center>
<h1>
<%= link_to_unless_current Rails.application.class.module_parent.name ,root_path %>
</h1>
<%= link_to_unless_current 'Inboxes' ,inboxes_path %>
<%= link_to_unless_current 'New Inboxes' ,new_inbox_path %>
<% if signed_in? %>
      <%=link_to current_user.email, edit_user_registration_path%>
      <%=button_to "Log Out", destroy_user_session_path , method: :delete ,
         data: {turbo: "false"}%>
    <%else%>
      <%=link_to "Log in", new_user_session_path%>
      <%=link_to "Register", new_user_registration_path%>
    <%end%>
</center>
<hr>
  

app/views/static_pages/landing_page.html.erb
<h1>StaticPages#landing_page</h1>
<p>Find me in app/views/static_pages/landing_page.html.erb</p>

app/views/static_pages/pricing.html.erb
<h1>StaticPages#pricing</h1>
<p>Find me in app/views/static_pages/pricing.html.erb</p>

app/views/static_pages/privacy.html.erb
<h1>StaticPages#privacy</h1>
<p>Find me in app/views/static_pages/privacy.html.erb</p>

app/views/static_pages/terms.html.erb
<h1>StaticPages#terms</h1>
<p>Find me in app/views/static_pages/terms.html.erb</p>